-- SentinelAPI PostgreSQL schema.
-- Logical tables and relationships mirror database/schema.sql without changing
-- the application-facing table or column contract.

CREATE TABLE IF NOT EXISTS openapi_specs (
    spec_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type TEXT NOT NULL
        CHECK (source_type IN ('url', 'upload')),
    source_url TEXT,
    title TEXT,
    spec_format TEXT NOT NULL
        CHECK (spec_format IN ('openapi', 'swagger')),
    api_version TEXT,
    raw_content TEXT,
    content_hash TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS api_scans (
    scan_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spec_id INTEGER NOT NULL,
    scan_name TEXT,
    target_base_url TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'queued'
        CHECK (status IN ('queued', 'running', 'completed', 'failed')),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (spec_id) REFERENCES openapi_specs (spec_id)
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS api_endpoints (
    endpoint_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id INTEGER NOT NULL,
    method TEXT NOT NULL,
    path TEXT NOT NULL,
    base_url TEXT NOT NULL,
    operation_id TEXT,
    parameters_json TEXT,
    response_schema_json TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (scan_id, method, path, base_url),
    FOREIGN KEY (scan_id) REFERENCES api_scans (scan_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS findings (
    finding_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id INTEGER NOT NULL,
    endpoint_id INTEGER,
    finding_type TEXT NOT NULL
        CHECK (finding_type IN (
            'BOLA_IDOR',
            'EXCESSIVE_DATA_EXPOSURE',
            'OTHER_SECURITY'
        )),
    title TEXT NOT NULL,
    severity TEXT NOT NULL
        CHECK (severity IN ('info', 'low', 'medium', 'high', 'critical')),
    confidence DOUBLE PRECISION NOT NULL
        CHECK (confidence >= 0.0 AND confidence <= 1.0),
    request_evidence_json TEXT,
    response_evidence_json TEXT,
    poc_text TEXT,
    details_json TEXT,
    explanation TEXT,
    impact TEXT,
    remediation TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (scan_id) REFERENCES api_scans (scan_id)
        ON DELETE CASCADE,
    FOREIGN KEY (endpoint_id) REFERENCES api_endpoints (endpoint_id)
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_api_scans_spec_id
    ON api_scans (spec_id);

CREATE INDEX IF NOT EXISTS idx_api_endpoints_scan_id
    ON api_endpoints (scan_id);

CREATE INDEX IF NOT EXISTS idx_findings_scan_id
    ON findings (scan_id);

CREATE INDEX IF NOT EXISTS idx_findings_endpoint_id
    ON findings (endpoint_id);

CREATE INDEX IF NOT EXISTS idx_findings_type
    ON findings (finding_type);

CREATE INDEX IF NOT EXISTS idx_findings_severity
    ON findings (severity);
